# Generated by Django 2.2 on 2020-12-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(default='', max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('branded', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='test.jpg', null=True, upload_to='shop')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=200)),
                ('discount', models.IntegerField()),
                ('old_price', models.CharField(default='', max_length=200)),
                ('is_approve', models.BooleanField(blank=True, default=False)),
                ('Shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sale.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(default='', max_length=200)),
                ('valid_from', models.DateTimeField()),
                ('valid_till', models.DateTimeField()),
                ('discount_per', models.CharField(default='', max_length=200)),
                ('is_approve', models.BooleanField(blank=True, default=False)),
                ('Shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sale.Shop')),
            ],
        ),
    ]
